name: edemand_partner
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+24

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  intl: any
  image_picker: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.1.1
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  shimmer: ^3.0.0
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.1
  table_calendar: ^3.0.8
  fl_chart: ^0.63.0
  cached_network_image: ^3.2.3
  rive: ^0.9.1
  version: ^3.0.2
  url_launcher: ^6.1.7
  package_info_plus: ^4.0.0
  country_calling_code_picker: ^2.0.1
  firebase_auth: ^4.1.0
  sms_autofill: ^2.2.0
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  change_app_package_name: ^1.1.0
  path_drawing: ^1.0.1
  file_picker: ^5.2.10
  video_player: ^2.6.1
  mime: ^1.0.3
  http_parser: ^4.0.2
  path: ^1.8.2
  quick_actions: ^1.0.2
  awesome_notifications: ^0.7.4+1
  open_filex: ^4.3.2
  html_editor_enhanced: ^2.5.1
  flutter_widget_from_html: ^0.10.1
  razorpay_flutter: ^1.3.5
  flutter_paystack: ^1.0.7
  flutter_stripe: ^9.3.0
  webview_flutter: ^4.0.7
  lottie: ^2.5.0
  readmore:
  flutter_typeahead: ^5.0.1


dependency_overrides:
  intl: ^0.17.0
  chewie:
    git:
      url: https://github.com/mdeimert/chewie.git
      ref: master

dev_dependencies:
  rename: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: 'assets/images/png/ic_laucher.png'
  ios: true
  android: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/languages/
    - assets/mapTheme/
    - assets/animation/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PLUSJAKARTASANS-MEDIUM.ttf
        - asset: assets/fonts/PLUSJAKARTASANS-BOLD.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
